title:              M. Serdar Karaman Blog
email:              serdar@karaman.dev
description:        A personal blog about software engineering, programing, C, C++, Qt, Python, Linux, Avionics and life
author:             M. Serdar Karaman
baseurl:            "/"
url:                "https://karaman.dev"
favicon:
  source: favicon.jpg
sass:
    style: compressed

# Social Profiles
twitter_username:
github_username:     Mavrikant
facebook_username:
instagram_username:
linkedin_username: mserdarkaraman
youtube_username: UCIlBH9QynIkHxX8uiY0UEMQ

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-YDEV31NZ5J

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-spaceship
  - jekyll-favicon
  - jekyll-coffeescript
