title:              M. Serdar Karaman Blog
email:              serdar@karaman.dev
description:        A personal blog about software engineering
author:             M. Serdar Karaman
baseurl:            "/"
url:                "https://www.karaman.dev"

# Social Profiles
twitter_username:   Mavrikant
github_username:    Mavrikant
facebook_username:  Mavrikant
instagram_username:  Mavrikant
linkedin_username: mserdarkaraman

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-YDEV31NZ5J # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
